channels:
  - conda-forge
  - robostack
  - robostack-staging
<<<<<<< HEAD
  #- pytorch
  #- pytorch3d
=======
  - pytorch
  - pytorch3d
  - nvidia
>>>>>>> 2e862e0e9af02b2347f2188917e89ce690db297d
dependencies:
  - python==3.9.*
  - ros-noetic-desktop
  - ros-noetic-ros-numpy
  - catkin_tools
  - cmake
  - pybind11
  - pinocchio
<<<<<<< HEAD
  # - pytorch==1.13.*  # Compatibility with pytorch3d
  # - pytorch3d
=======
  - pytorch==1.13.*  # Compatibility with pytorch3d
  - pytorch-cuda=11.7
  - pytorch3d
  - opencv
>>>>>>> 2e862e0e9af02b2347f2188917e89ce690db297d
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
<<<<<<< HEAD
    - opencv-python>=3.3.0
=======
>>>>>>> 2e862e0e9af02b2347f2188917e89ce690db297d
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    # Neural networks
    - openai-clip
    - timm
    - pandas
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - h5py
    - imageio
    - pygifsicle
    - pynput
