defaults:
  - _self_
  - dataset: scannet
  - model: instancemap3d_top_down
  - paths: default
  - hydra: default

scene_name: scene0011_00
show_backend: false # open3d, pytorch3d
save_instance_map_fpath: ./canned_scannet_scene.pth
task_name: 'huh'