arm:
  default:
    accel_m: 0.14
    vel_m: 0.14
  fast:
    accel_m: 0.3
    vel_m: 0.3
  max:
    accel_m: 0.4
    vel_m: 0.4
  slow:
    accel_m: 0.05
    vel_m: 0.05
  trajectory_max:
    accel_m: 0.4
    vel_m: 0.4
base:
  default:
    accel_m: 0.12
    vel_m: 0.12
  fast:
    accel_m: 0.25
    vel_m: 0.25
  max:
    accel_m: 0.3
    vel_m: 0.3
  slow:
    accel_m: 0.06
    vel_m: 0.04
  trajectory_max:
    accel_r: 30.0
    vel_r: 50.0
head_pan:
  default:
    accel: 8.0
    vel: 3.0
  fast:
    accel: 10.0
    vel: 5.0
  max:
    accel: 14.0
    vel: 7.0
  slow:
    accel: 4.0
    vel: 1.0
  trajectory_max:
    accel_r: 16.0
    vel_r: 8.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
head_tilt:
  default:
    accel: 8.0
    vel: 3.0
  fast:
    accel: 10.0
    vel: 5.0
  max:
    accel: 14.0
    vel: 7.0
  slow:
    accel: 4.0
    vel: 1.0
  trajectory_max:
    accel_r: 16.0
    vel_r: 8.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
hello-motor-arm:
  accel: 15
  vel: 25
hello-motor-left-wheel:
  accel: 15
  vel: 25
hello-motor-lift:
  accel: 15
  vel: 12
hello-motor-right-wheel:
  accel: 15
  vel: 25
lift:
  default:
    accel_m: 0.2
    vel_m: 0.11
  fast:
    accel_m: 0.25
    vel_m: 0.13
  max:
    accel_m: 0.3
    vel_m: 0.15
  slow:
    accel_m: 0.05
    vel_m: 0.05
  trajectory_max:
    accel_m: 0.3
    vel_m: 0.15
stretch_gripper:
  default:
    accel: 10.0
    vel: 4.0
  fast:
    accel: 10.0
    vel: 6.0
  max:
    accel: 12
    vel: 8
  slow:
    accel: 4.0
    vel: 2.0
  trajectory_max:
    accel_r: 100.0
    vel_r: 50.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
wrist_pitch:
  default:
    accel: 6.0
    vel: 2.0
  fast:
    accel: 8.0
    vel: 4.0
  max:
    accel: 10.0
    vel: 5.0
  slow:
    accel: 4.0
    vel: 1.0
  trajectory_max:
    accel_r: 16.0
    vel_r: 8.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
wrist_roll:
  default:
    accel: 8.0
    vel: 3.0
  fast:
    accel: 10.0
    vel: 5.0
  max:
    accel: 12
    vel: 8
  slow:
    accel: 4.0
    vel: 1.0
  trajectory_max:
    accel_r: 16.0
    vel_r: 8.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
wrist_yaw:
  default:
    accel: 3.0
    vel: 2.0
  fast:
    accel: 5.0
    vel: 2.5
  max:
    accel: 10
    vel: 6.0
  slow:
    accel: 1.5
    vel: 0.75
  trajectory_max:
    accel_r: 3.0
    vel_r: 3.0
  trajectory_vel_ctrl: 1
  trajectory_vel_ctrl_kP: 1.5
