device: "cuda"

# Data params
# Image width and height before passing to models
desired_height: 256
desired_width: 256

# Voxel params
voxel_size: 0.05

# SAM params
SAM_checkpoint_path: "/srv/flash1/kyadav32/datasets/ovmm/sam/sam_vit_h_4b8939.pth"
model_type: "vit_h"
# Ignore masks that have valid pixels less than this fraction (of the image area)
bbox_area_thresh: 0.0005
# Number of query points (grid size) to be sampled by SAM
points_per_side: 32

# CLIP model paramsß
open_clip_model: "ViT-H-14"
open_clip_pretrained_dataset: "laion2b_s32b_b79k"

# DBSCAN params
epsilon: 0.3
min_samples: 25

# Similarity params
viz_type: "thresh" # "topk" or "thresh"
similarity_thresh: 0.9
topk: 1000

# Directory to save extracted features
save_path: "saved-feat"
save_images: False
voxel_map_file: "None" #"/srv/flash1/kyadav32/code/ovmm/home-robot/projects/real_world_ovmm/experimental/voxel_map_512x512.pkl"
