name:
  slap_base
channels:
  - conda-forge
  - default
  - pytorch
dependencies:
  - python=3.9
  - trimesh
  - h5py
  - imageio
  - pdbpp
  - mypy
  - pylint
  - pinocchio
  - cmake
  - pybind11
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - opencv-python>=3.3.0
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - numpy-quaternion
    # Neural networks
    - openai-clip
    - timm
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - pygifsicle
    - perceiver-pytorch
    - wandb
    - hydra-core
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch==1.12.1+cu116
    - torchaudio==0.12.1
    - torchvision==0.13.1+cu116
    - --file https://data.pyg.org/whl/torch-1.12.1+cu116.html
    - pyg_lib
    - torch_scatter 
    - torch_sparse
    - torch_cluster
    - torch_spline_conv 
    - torch_geometric

