_target_: home_robot.mapping.voxel.SparseVoxelMap
resolution: 0.01
background_instance_label: -1
instance_memory_kwargs:
    erode_mask_num_pix: 5
    erode_mask_num_iter: 5
    iou_threshold: 0.3
    instance_association: 'bbox_one_sided_iou'
