defaults:
  - tasks@: imagenav
  - experiments@: imagenav_rl
  - model: mae_vit_base_patch16_ego_imagenet_inav_182_epochs
  - model/transform: jitter_and_shift
  - wandb_habitat@: habitat_eaif
  - override hydra/output: path
  - _self_

checkpoint_path: "/home/cortex/home-robot/projects/imagenav/models/imagenav_stretch_embodiement_780m_may10.pth"
stretch_goal_image_path: "/home/cortex/home-robot/projects/imagenav/image_goals/goal_image_11.png"  # path to the goal image to be used in physical stretch operation

RUN_TYPE: eval
NUM_ENVIRONMENTS: 1
TASK_CONFIG:
  SIMULATOR:
    AGENT_0:
      HEIGHT: 1.41
      RADIUS: 0.30
      SENSORS: ["RGB_SENSOR"]
    RGB_SENSOR:
      WIDTH: 120
      HEIGHT: 160
      HFOV: 42
      POSITION: [0, 1.31, 0]
      ORIENTATION: [-0.1745, 0.0, 0.0]

RL:
  POLICY:
    use_augmentations: False
    use_augmentations_test_time: False
    freeze_backbone: True
    input_image_size: [160, 120] 