defaults:
  - tasks@: imagenav
  - experiments@: imagenav_rl
  - model: mae_vit_base_patch16_ego_imagenet_inav_182_epochs
  - model/transform: jitter_and_shift
  - wandb_habitat@: habitat_eaif
  - override hydra/output: path
  - _self_

#checkpoint_path: "/home/cortex/home-robot/projects/imagenav/models/imagenav_stretch_500m_apr4.pth"
checkpoint_path: "/home/cortex/home-robot/projects/imagenav/models/imagenav_stretch_1500m_apr12.pth"
stretch_goal_image_path: "/home/cortex/home-robot/projects/imagenav/image_goals/goal_image.png"  # path to the goal image to be used in physical stretch operation

RUN_TYPE: eval
NUM_ENVIRONMENTS: 14
TASK_CONFIG:
  SIMULATOR:
    AGENT_0:
      HEIGHT: 1.41
      RADIUS: 0.17
    RGB_SENSOR:
      WIDTH: 128
      HEIGHT: 128
      HFOV: 42
      POSITION: [0, 1.31, 0]
